import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";

const Home: NextPage = () => {
  const [dataPokemons, setDataPokemons] = useState<any>([]);

  const getPokemons = async () => {
    const response = await fetch("https://pokeapi.co/api/v2/pokemon/");
    const data = await response.json();
    setDataPokemons(data.results);
  };

  //Obtener id de la url
  const getId = (url: string) => {
    const id = url.split("/");   
    return id[id.length - 2];
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={getPokemons}>Get Pokemons</button>
        <ul>
          {dataPokemons ? (
            dataPokemons.map((pokemon: any) => (              
              <li key={pokemon.name}>                             
                <Link href={`/pokemon/${getId(pokemon.url)}`}>
                  <a>{pokemon.name}</a>                  
                </Link>
              </li>
            ))
          ) : (
            <li>Loading...</li>
          )}
        </ul>
      </main>
    </div>
  );
};

export default Home;
